# comment
# (note: the <tab> in the command line is necessary for make to work) 
#target:  dependency1 dependency2 ...
#      <tab> command

#for example:
#
# target entry to build program executable from program and mylib 
# object files 
#

all: clean build
	#bash build.sh

build:
	bash build.sh

clean: 
	  $(RM) ass2
	  $(RM) output.txt
