# comment
# (note: the <tab> in the command line is necessary for make to work) 
#target:  dependency1 dependency2 ...
#      <tab> command

#for example:
#
# target entry to build program executable from program and mylib 
# object files 
#

all:
	bash build.sh
#	gcc -Wall -Werror -o ass2 ass2.c -pthread

clean: 
	  $(RM) ass
